### ISSUE TITLE
Update minizinc to latest version

### ISSUE THREAD

**Issue by eberhardinger** [inz/minizinc-dist#1]
Hi there,
is there any chance to update the package to version 2.2 or newer?

Best

**Comment by inz** [comment]
Unfortunately, MiniZinc stopped providing standalone binary releases for `libminizinc`. We'd need to switch to [MiniZincIDE releases](https://github.com/MiniZinc/minizincide/releases) starting with version 2.1.7.

I'm not actively using MiniZinc at the moment, but I'd be happy to merge a PR for the version update.

**Comment by eberhardinger** [comment]
Thanks for the quick reply. I forked your repo and integrated the MiniZincIDE release URL and created a new release in my fork. If you like, feel free to merge it into your repo. 
Thanks a lot for providing the scripts!
